sudo: required
language: node_js
node_js: "7.0"

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - if [[ 'npm -v' == 3* ]]; then npm i -g npm@4; fi
  - npm --version
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g angular-cli@latest
  - npm install -g karma
  - npm install

after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  bash deploy.sh

env:
  global:
    - secure: >-
        JAY/gjKP72SUATHObnZ6xayPKW2FD6x8MnUPCKa7aAHW3UtV5uSdO8sf/TcB4wo0MXA3c5L0sbzJ1aF0Y77PtY8OkYG/O2igA+w87Lr86o1jWyRBpNMZJkIOB5xE471EpYuv6ELleI1oqttBp8bzSblQ5K1ilCCj/EalXiiYO62uka8m2osy1MkvVTSjRcnrBEsKb/aw3Aw3lzK9TejAyQW+DpVMsaGRdQnJQyBru7GssGQZyjFmqLRKWv09+3fyE1spn0qcwMj0VAN/ruVuoQtuHNI878fs6JOLstk92BfQY2jAzzIjDX22BWHh9CnkASkYME4NWwHbZhans+CErmFT7qDmw+65WRm3Vrez+k1VPPqL6VL9uXnqEYlSqBnsn+oYOIFDwF3m24eAu4XbI1Rpm+WzMxFhftvV3sfXeiNXDj9scb7rOE6kMeEl1atmcFYD614snD5Mppw4OsV1f3uMb+q6vTL2X1FxLtSZM33jbZK60UiQv3wqY9Uyd3rbL6Ut3/wf+5fSoP8X+O7wIbxTb+jloDUkzSGTNixSLpo8jCiwJrdVN6uMULrEFVdBPRIADNp3vMvhzLVG9tPV6uT/efQ50vpjTvnCkJ+gaJ3MA3nke8UTMYXI2+U5W/NGL3DZsuYw5GpZTitQSSPkqRDjkE8gsv8nHgU+wMvFtbI=
